# Default initial positions for armstrong_urdf_v11's ros2_control fake system

initial_positions:
  joint1_right: 0
  joint2_right: 0
  joint3_right: 0
  joint4_right: 0
  joint5_right: 0
  joint6_right: 0